### PR TITLE
wget the dataset in Travis CI

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
Sorry...  I should have put _work in progress_ on this one...  It does not work yet.

**Comment by YadiraF** [comment]
It's ok. Just pull again when you finished. Really appreciate your contribution!

**Comment by YadiraF** [comment]
Sorry, I don't know referer_url. Maybe I will share the links of Baidu drive file in another way. I will search this. 
I only run on python 2 now.

**Comment by cclauss** [comment]
Today there are __600 days left__ until [Python 2 end of life](https://pythonclock.org):
```python
from datetime import date
print((date(2020, 1, 1) - http://date.today()).days, 'days until Python 2 end of life.')
```

**Pull request merged**
